---
# tasks file for vault-ssh-helper
- name: Generate /etc/ssh/vault.hcl
  template:
    src: vault.hcl.j2
    dest: /etc/ssh/vault.hcl
    owner: root
    group: root
    mode: 0644

- name: Install unzip
  apt:
    name: unzip
    state: present

- name: Install libpam-ssh
  apt:
    name: libpam-ssh
    state: present

- name: Create /etc/pam.d/sshd
  copy:
    src: "{{ vault_ssh_helper_sshd|default('sshd') }}"
    dest: /etc/pam.d/sshd
    owner: root
    group: root
    mode: 0644

- replace:
    path: /etc/ssh/sshd_config
    regexp: '^ChallengeResponseAuthentication no$'
    replace: 'ChallengeResponseAuthentication yes'
    backup: yes
- replace:
    path: /etc/ssh/sshd_config
    regexp: '^UsePAM no$'
    replace: 'UsePAM yes'
    backup: yes

- name: Install binary
  unarchive:
    src: "{{ vault_ssh_helper_repo_url }}" 
    dest: /usr/bin
    mode: 0755
    remote_src: yes

- name: Restart sshd
  systemd:
    state: restarted
    name: sshd
